version: 2.1
workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build-binaries:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  test:
    docker:
      - image: cimg/go:1.14
    environment:
      CGO_ENABLED: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "src/go.sum" }}
      - run:
          name: "Download Dependancies"
          command: cd src && go mod download
      - run:
          name: "Run Tests"
          command: cd src && go test
      - save_cache:
          key: go-mod-v1-{{ checksum "src/go.sum" }} 
          paths:
            - "/go/pkg/mod"
  build-binaries:
    parameters:
      publish:
        type: boolean
        default: false
    docker:
      - image: cibuilds/goreleaser:0.120
    steps:
      - checkout
      - run:
          name: "Build and Optionally Publish Binaries"
          command: |
            if [[ $CIRCLE_TAG != "" ]];then
              cd src && goreleaser
            else
              cd src && goreleaser --snapshot --skip-publish --rm-dist
            fi
      - run:
          name: "Run File Tests"
          command: |
            src/dist/md-proofer_linux_amd64/md-proofer version

            if src/dist/md-proofer_linux_amd64/md-proofer lint good-test-files/; then
              echo "md-proofer passed the files. Continue on."
            else
              echo "The tests failed, which it shouldn't. Something is wrong."
              exit 1
            fi

            if src/dist/md-proofer_linux_amd64/md-proofer lint bad-test-files/; then
              echo "md-proofer returned an exit code of 0, which shouldn't be the case."
              exit 1
            else
              echo "The tests failed, which is what we expected. Continue on."
            fi

            if src/dist/md-proofer_linux_amd64/md-proofer lint good-test-files/ bad-test-files/; then
              echo "md-proofer returned an exit code of 0, which shouldn't be the case."
              exit 1
            else
              echo "Some of the tests failed, which is what we expected. Continue on."
            fi
